// ── Trivia Questions Bank ────────────────────────────────────────────

export interface TriviaQuestion {
  question: string;
  options: [string, string, string, string];
  correctIndex: number;
  category: string;
  funFact?: string;
  difficulty: 'easy' | 'medium' | 'hard';
}

export const triviaQuestions: TriviaQuestion[] = [
  // ══════════════════════════════════════════════════════════════════
  // GHANA HISTORY (30)
  // ══════════════════════════════════════════════════════════════════
  {
    question: 'In what year did Ghana gain independence from Britain?',
    options: ['1954', '1957', '1960', '1963'],
    correctIndex: 1,
    category: 'Ghana History',
    funFact: 'Ghana was the first sub-Saharan African country to gain independence.',
    difficulty: 'easy',
  },
  {
    question: 'Who was the first President of Ghana?',
    options: ['J.B. Danquah', 'Kwame Nkrumah', 'Edward Akufo-Addo', 'Kofi Busia'],
    correctIndex: 1,
    category: 'Ghana History',
    funFact: 'Nkrumah was also a key figure in the Pan-African movement.',
    difficulty: 'easy',
  },
  {
    question: 'What was the colonial name of Ghana?',
    options: ['Ivory Coast', 'Gold Coast', 'Slave Coast', 'Grain Coast'],
    correctIndex: 1,
    category: 'Ghana History',
    funFact: 'The name "Gold Coast" came from the abundance of gold in the region.',
    difficulty: 'easy',
  },
  {
    question: 'On what date is Ghana\'s Independence Day celebrated?',
    options: ['January 1', 'March 6', 'July 1', 'December 25'],
    correctIndex: 1,
    category: 'Ghana History',
    difficulty: 'easy',
  },
  {
    question: 'Which party did Kwame Nkrumah lead to independence?',
    options: ['UGCC', 'CPP', 'NLM', 'NPP'],
    correctIndex: 1,
    category: 'Ghana History',
    funFact: 'CPP stands for Convention People\'s Party, founded in 1949.',
    difficulty: 'medium',
  },
  {
    question: 'What year did Ghana become a Republic?',
    options: ['1957', '1958', '1960', '1966'],
    correctIndex: 2,
    category: 'Ghana History',
    difficulty: 'medium',
  },
  {
    question: 'Who was the Ashanti Queen Mother who fought the British in 1900?',
    options: ['Yaa Asantewaa', 'Nana Afia Kobi', 'Nana Yaa Akyaa', 'Afua Kobi'],
    correctIndex: 0,
    category: 'Ghana History',
    funFact: 'The Yaa Asantewaa War was the last major war led by an African woman.',
    difficulty: 'easy',
  },
  {
    question: 'Which dam created Lake Volta, the world\'s largest artificial lake by surface area?',
    options: ['Bui Dam', 'Kpong Dam', 'Akosombo Dam', 'Weija Dam'],
    correctIndex: 2,
    category: 'Ghana History',
    funFact: 'Lake Volta covers about 3.6% of Ghana\'s total land area.',
    difficulty: 'medium',
  },
  {
    question: 'What was the "Big Six" in Ghanaian history?',
    options: ['Six major rivers', 'Six founding fathers of independence movement', 'Six colonial forts', 'Six Ashanti kings'],
    correctIndex: 1,
    category: 'Ghana History',
    difficulty: 'medium',
  },
  {
    question: 'In what year was the UGCC (United Gold Coast Convention) founded?',
    options: ['1945', '1947', '1949', '1951'],
    correctIndex: 1,
    category: 'Ghana History',
    difficulty: 'hard',
  },
  {
    question: 'Which Governor built Korle Bu Teaching Hospital?',
    options: ['Gordon Guggisberg', 'Alan Burns', 'Charles Arden-Clarke', 'Frederick Hodgson'],
    correctIndex: 0,
    category: 'Ghana History',
    difficulty: 'hard',
  },
  {
    question: 'What was the 1948 Accra riots triggered by?',
    options: ['Tax increases', 'Shooting of ex-servicemen', 'Food shortages', 'Land disputes'],
    correctIndex: 1,
    category: 'Ghana History',
    funFact: 'Three ex-servicemen — Sergeant Adjetey, Corporal Attipoe, and Private Odartey Lamptey — were shot.',
    difficulty: 'hard',
  },
  {
    question: 'The Bond of 1844 was signed between the British and which group?',
    options: ['Ashanti chiefs', 'Fante chiefs', 'Ga chiefs', 'Ewe chiefs'],
    correctIndex: 1,
    category: 'Ghana History',
    difficulty: 'hard',
  },
  {
    question: 'Who overthrew Nkrumah\'s government in 1966?',
    options: ['NLC (National Liberation Council)', 'SMC', 'PNDC', 'AFRC'],
    correctIndex: 0,
    category: 'Ghana History',
    difficulty: 'medium',
  },
  {
    question: 'What was Ghana\'s main export commodity in the colonial era?',
    options: ['Diamonds', 'Cocoa', 'Timber', 'Palm oil'],
    correctIndex: 1,
    category: 'Ghana History',
    funFact: 'Ghana was once the world\'s largest cocoa producer.',
    difficulty: 'easy',
  },
  {
    question: 'Which Ashanti king was exiled to the Seychelles by the British?',
    options: ['Osei Tutu I', 'Prempeh I', 'Opoku Ware I', 'Osei Bonsu'],
    correctIndex: 1,
    category: 'Ghana History',
    difficulty: 'medium',
  },
  {
    question: 'What does "Osagyefo" mean, the title given to Nkrumah?',
    options: ['The Great One', 'The Redeemer', 'The Wise One', 'The Brave One'],
    correctIndex: 1,
    category: 'Ghana History',
    difficulty: 'medium',
  },
  {
    question: 'Which castle served as the seat of government until 2013?',
    options: ['Cape Coast Castle', 'Elmina Castle', 'Christiansborg Castle', 'Fort William'],
    correctIndex: 2,
    category: 'Ghana History',
    difficulty: 'medium',
  },
  {
    question: 'The Trans-Volta Togoland joined Ghana through what process in 1956?',
    options: ['Military conquest', 'Plebiscite', 'Treaty', 'UN mandate'],
    correctIndex: 1,
    category: 'Ghana History',
    difficulty: 'hard',
  },
  {
    question: 'Who introduced cocoa farming to Ghana?',
    options: ['Tetteh Quarshie', 'Kwame Nkrumah', 'J.B. Danquah', 'Governor Guggisberg'],
    correctIndex: 0,
    category: 'Ghana History',
    funFact: 'Tetteh Quarshie brought cocoa beans from Fernando Po (now Bioko) in 1879.',
    difficulty: 'easy',
  },
  {
    question: 'What year did J.J. Rawlings first come to power?',
    options: ['1975', '1979', '1981', '1983'],
    correctIndex: 1,
    category: 'Ghana History',
    difficulty: 'medium',
  },
  {
    question: 'The Fourth Republic of Ghana began in what year?',
    options: ['1988', '1990', '1992', '1996'],
    correctIndex: 2,
    category: 'Ghana History',
    funFact: 'The 1992 Constitution established the Fourth Republic.',
    difficulty: 'medium',
  },
  {
    question: 'What Pan-African organization did Nkrumah help establish?',
    options: ['African Union', 'Organisation of African Unity', 'ECOWAS', 'African Development Bank'],
    correctIndex: 1,
    category: 'Ghana History',
    difficulty: 'hard',
  },
  {
    question: 'Which school was established by Governor Guggisberg in 1927?',
    options: ['Mfantsipim School', 'Achimota School', 'Adisadel College', 'Prempeh College'],
    correctIndex: 1,
    category: 'Ghana History',
    difficulty: 'medium',
  },
  {
    question: 'What was the name of the first political party in the Gold Coast?',
    options: ['CPP', 'ARPS', 'UGCC', 'NLM'],
    correctIndex: 1,
    category: 'Ghana History',
    funFact: 'ARPS stands for Aborigines\' Rights Protection Society, formed in 1897.',
    difficulty: 'hard',
  },
  {
    question: 'Operation Cold Chop refers to which event?',
    options: ['A famine relief program', 'The 1966 coup against Nkrumah', 'A military exercise', 'An economic policy'],
    correctIndex: 1,
    category: 'Ghana History',
    difficulty: 'hard',
  },
  {
    question: 'Who was the first African-born Governor of the Gold Coast?',
    options: ['There was none', 'John Mensah Sarbah', 'Nana Ofori Atta', 'Paa Grant'],
    correctIndex: 0,
    category: 'Ghana History',
    difficulty: 'hard',
  },
  {
    question: 'The Manhyia Palace is the seat of which traditional leader?',
    options: ['Ga Mantse', 'Asantehene', 'Okyenhene', 'Dagbon Ya-Na'],
    correctIndex: 1,
    category: 'Ghana History',
    difficulty: 'easy',
  },
  {
    question: 'What year was the University of Ghana established?',
    options: ['1945', '1948', '1951', '1957'],
    correctIndex: 1,
    category: 'Ghana History',
    funFact: 'Originally called the University College of the Gold Coast.',
    difficulty: 'hard',
  },
  {
    question: 'What does the Black Star on Ghana\'s flag represent?',
    options: ['The night sky', 'African emancipation', 'Mining industry', 'The Atlantic Ocean'],
    correctIndex: 1,
    category: 'Ghana History',
    difficulty: 'easy',
  },

  // ══════════════════════════════════════════════════════════════════
  // GHANA GEOGRAPHY (25)
  // ══════════════════════════════════════════════════════════════════
  {
    question: 'What is the capital city of Ghana?',
    options: ['Kumasi', 'Accra', 'Tamale', 'Cape Coast'],
    correctIndex: 1,
    category: 'Ghana Geography',
    difficulty: 'easy',
  },
  {
    question: 'Lake Volta is the world\'s largest artificial lake by what measure?',
    options: ['Volume', 'Depth', 'Surface area', 'Length'],
    correctIndex: 2,
    category: 'Ghana Geography',
    difficulty: 'medium',
  },
  {
    question: 'How many regions does Ghana currently have?',
    options: ['10', '12', '14', '16'],
    correctIndex: 3,
    category: 'Ghana Geography',
    funFact: 'Ghana increased from 10 to 16 regions after a 2018 referendum.',
    difficulty: 'easy',
  },
  {
    question: 'Which region is Kumasi the capital of?',
    options: ['Eastern', 'Ashanti', 'Bono', 'Central'],
    correctIndex: 1,
    category: 'Ghana Geography',
    difficulty: 'easy',
  },
  {
    question: 'What body of water borders Ghana to the south?',
    options: ['Indian Ocean', 'Atlantic Ocean', 'Gulf of Guinea', 'Mediterranean Sea'],
    correctIndex: 2,
    category: 'Ghana Geography',
    difficulty: 'easy',
  },
  {
    question: 'Which national park in Ghana is famous for its canopy walkway?',
    options: ['Mole', 'Kakum', 'Bui', 'Digya'],
    correctIndex: 1,
    category: 'Ghana Geography',
    difficulty: 'easy',
  },
  {
    question: 'Mount Afadja is the highest point in Ghana. In which region is it located?',
    options: ['Ashanti', 'Volta', 'Eastern', 'Northern'],
    correctIndex: 1,
    category: 'Ghana Geography',
    difficulty: 'medium',
  },
  {
    question: 'Which country does NOT share a border with Ghana?',
    options: ['Togo', 'Ivory Coast', 'Burkina Faso', 'Nigeria'],
    correctIndex: 3,
    category: 'Ghana Geography',
    difficulty: 'easy',
  },
  {
    question: 'Cape Coast Castle is a UNESCO World Heritage Site associated with what?',
    options: ['Gold mining', 'Slave trade', 'Cocoa export', 'Traditional festivals'],
    correctIndex: 1,
    category: 'Ghana Geography',
    funFact: 'Cape Coast Castle was one of about 40 slave forts on the Gold Coast.',
    difficulty: 'easy',
  },
  {
    question: 'Which is the largest region in Ghana by land area?',
    options: ['Ashanti', 'Northern', 'Savannah', 'Brong-Ahafo'],
    correctIndex: 2,
    category: 'Ghana Geography',
    difficulty: 'hard',
  },
  {
    question: 'The Volta River flows into which body of water?',
    options: ['Lake Chad', 'Gulf of Guinea', 'Niger River', 'Atlantic Ocean'],
    correctIndex: 1,
    category: 'Ghana Geography',
    difficulty: 'medium',
  },
  {
    question: 'Tema is known primarily as Ghana\'s major what?',
    options: ['Fishing village', 'Industrial port city', 'Tourist resort', 'Agricultural center'],
    correctIndex: 1,
    category: 'Ghana Geography',
    difficulty: 'easy',
  },
  {
    question: 'Which Ghanaian city is known as the "Garden City"?',
    options: ['Accra', 'Tamale', 'Kumasi', 'Ho'],
    correctIndex: 2,
    category: 'Ghana Geography',
    difficulty: 'medium',
  },
  {
    question: 'The Greenwich Meridian (0 degrees longitude) passes through which Ghanaian city?',
    options: ['Kumasi', 'Accra', 'Tema', 'Takoradi'],
    correctIndex: 2,
    category: 'Ghana Geography',
    funFact: 'Tema is one of the few cities in the world where the Greenwich Meridian passes through.',
    difficulty: 'medium',
  },
  {
    question: 'Mole National Park is located in which part of Ghana?',
    options: ['Southern coast', 'Eastern highlands', 'Northern savannah', 'Central forest'],
    correctIndex: 2,
    category: 'Ghana Geography',
    difficulty: 'medium',
  },
  {
    question: 'Which river forms part of Ghana\'s western border?',
    options: ['Volta', 'Tano', 'Pra', 'Ankobra'],
    correctIndex: 1,
    category: 'Ghana Geography',
    difficulty: 'hard',
  },
  {
    question: 'Obuasi is famous for what mineral resource?',
    options: ['Diamond', 'Bauxite', 'Gold', 'Manganese'],
    correctIndex: 2,
    category: 'Ghana Geography',
    difficulty: 'easy',
  },
  {
    question: 'The Kwahu Plateau is known for which annual event?',
    options: ['Hogbetsotso', 'Easter celebrations', 'Homowo', 'Aboakyir'],
    correctIndex: 1,
    category: 'Ghana Geography',
    difficulty: 'medium',
  },
  {
    question: 'Which city is the capital of the Western Region?',
    options: ['Tarkwa', 'Takoradi', 'Sekondi-Takoradi', 'Axim'],
    correctIndex: 2,
    category: 'Ghana Geography',
    difficulty: 'medium',
  },
  {
    question: 'Ada Foah is located at the mouth of which river?',
    options: ['Pra', 'Ankobra', 'Volta', 'Densu'],
    correctIndex: 2,
    category: 'Ghana Geography',
    difficulty: 'medium',
  },
  {
    question: 'Which Ghanaian region was created most recently (2018-2019)?',
    options: ['Oti Region', 'All four new regions were created simultaneously', 'North East Region', 'Western North Region'],
    correctIndex: 1,
    category: 'Ghana Geography',
    difficulty: 'hard',
  },
  {
    question: 'What is the approximate total land area of Ghana?',
    options: ['92,000 sq km', '148,000 sq km', '239,000 sq km', '324,000 sq km'],
    correctIndex: 2,
    category: 'Ghana Geography',
    difficulty: 'hard',
  },
  {
    question: 'The Wli Waterfalls, the highest in West Africa, are in which region?',
    options: ['Eastern', 'Volta', 'Oti', 'Ashanti'],
    correctIndex: 1,
    category: 'Ghana Geography',
    funFact: 'Wli Falls has an upper and lower section, with the upper falls reaching about 80 meters.',
    difficulty: 'medium',
  },
  {
    question: 'Elmina Castle was built by which European nation?',
    options: ['British', 'Dutch', 'Portuguese', 'Danish'],
    correctIndex: 2,
    category: 'Ghana Geography',
    funFact: 'Built in 1482, it is the oldest European building in sub-Saharan Africa.',
    difficulty: 'medium',
  },
  {
    question: 'Which strait or channel separates Ghana from any island?',
    options: ['There is no such strait', 'Strait of Accra', 'Gulf Channel', 'Volta Strait'],
    correctIndex: 0,
    category: 'Ghana Geography',
    difficulty: 'hard',
  },

  // ══════════════════════════════════════════════════════════════════
  // GHANA CULTURE (25)
  // ══════════════════════════════════════════════════════════════════
  {
    question: 'What does the Adinkra symbol "Sankofa" represent?',
    options: ['Strength', 'Learn from the past', 'Unity', 'Faith in God'],
    correctIndex: 1,
    category: 'Ghana Culture',
    funFact: 'Sankofa literally means "go back and get it" in Twi.',
    difficulty: 'easy',
  },
  {
    question: 'Fufu is typically made from which main ingredients?',
    options: ['Rice and beans', 'Cassava and plantain', 'Yam and corn', 'Millet and sorghum'],
    correctIndex: 1,
    category: 'Ghana Culture',
    difficulty: 'easy',
  },
  {
    question: 'Kente cloth originated from which ethnic group?',
    options: ['Ga-Adangbe', 'Ewe', 'Ashanti', 'Both Ashanti and Ewe'],
    correctIndex: 3,
    category: 'Ghana Culture',
    funFact: 'Both the Ashanti and Ewe people have distinct kente weaving traditions.',
    difficulty: 'medium',
  },
  {
    question: 'What is the Homowo festival associated with?',
    options: ['Harvest', 'Victory over hunger', 'New Year', 'Ancestor remembrance'],
    correctIndex: 1,
    category: 'Ghana Culture',
    funFact: 'Homowo literally means "hooting at hunger" and is celebrated by the Ga people.',
    difficulty: 'medium',
  },
  {
    question: 'The Adinkra symbol "Gye Nyame" represents what?',
    options: ['Bravery', 'Supremacy of God', 'Wisdom', 'Unity'],
    correctIndex: 1,
    category: 'Ghana Culture',
    funFact: 'Gye Nyame is the most popular Adinkra symbol.',
    difficulty: 'easy',
  },
  {
    question: 'Jollof rice is a staple dish. What gives it its distinctive color?',
    options: ['Saffron', 'Turmeric', 'Tomatoes', 'Red palm oil'],
    correctIndex: 2,
    category: 'Ghana Culture',
    difficulty: 'easy',
  },
  {
    question: 'What is "Azonto"?',
    options: ['A traditional soup', 'A dance style', 'A type of cloth', 'A festival'],
    correctIndex: 1,
    category: 'Ghana Culture',
    funFact: 'Azonto dance became internationally popular around 2011-2012.',
    difficulty: 'easy',
  },
  {
    question: 'The Golden Stool is sacred to which ethnic group?',
    options: ['Ga', 'Fante', 'Ashanti', 'Dagomba'],
    correctIndex: 2,
    category: 'Ghana Culture',
    funFact: 'The Golden Stool is believed to contain the spirit of the Ashanti nation.',
    difficulty: 'easy',
  },
  {
    question: 'Which festival involves the hunting of a live deer?',
    options: ['Homowo', 'Aboakyir', 'Hogbetsotso', 'Damba'],
    correctIndex: 1,
    category: 'Ghana Culture',
    funFact: 'Aboakyir is celebrated by the Effutu people of Winneba.',
    difficulty: 'medium',
  },
  {
    question: 'What is "Kenkey" made from?',
    options: ['Corn (maize)', 'Cassava', 'Rice', 'Millet'],
    correctIndex: 0,
    category: 'Ghana Culture',
    difficulty: 'easy',
  },
  {
    question: 'The Damba festival is celebrated by which people?',
    options: ['Ashanti', 'Ga', 'Dagomba', 'Ewe'],
    correctIndex: 2,
    category: 'Ghana Culture',
    difficulty: 'medium',
  },
  {
    question: 'What Adinkra symbol represents "unity and human relations"?',
    options: ['Nkonsonkonson', 'Dwennimmen', 'Sankofa', 'Adinkrahene'],
    correctIndex: 0,
    category: 'Ghana Culture',
    difficulty: 'medium',
  },
  {
    question: 'Ananse stories are folk tales featuring what creature?',
    options: ['Tortoise', 'Hare', 'Spider', 'Eagle'],
    correctIndex: 2,
    category: 'Ghana Culture',
    funFact: 'Ananse is a trickster figure who uses wit and cunning.',
    difficulty: 'easy',
  },
  {
    question: 'What is "Chichinga" in Ghanaian street food?',
    options: ['Fried plantain', 'Grilled meat skewers (kebabs)', 'Bean cake', 'Meat pie'],
    correctIndex: 1,
    category: 'Ghana Culture',
    difficulty: 'easy',
  },
  {
    question: 'Highlife music originated in which country?',
    options: ['Nigeria', 'Ghana', 'Senegal', 'Cameroon'],
    correctIndex: 1,
    category: 'Ghana Culture',
    funFact: 'Highlife emerged in the early 20th century, blending local and Western music.',
    difficulty: 'medium',
  },
  {
    question: 'What does "Akwaaba" mean?',
    options: ['Goodbye', 'Thank you', 'Welcome', 'Please'],
    correctIndex: 2,
    category: 'Ghana Culture',
    difficulty: 'easy',
  },
  {
    question: 'Fantasy coffins, made in unique shapes, originated near which city?',
    options: ['Kumasi', 'Tamale', 'Accra (Teshie)', 'Cape Coast'],
    correctIndex: 2,
    category: 'Ghana Culture',
    funFact: 'Fantasy coffins can be shaped like cars, fish, cocoa pods, or anything meaningful to the deceased.',
    difficulty: 'medium',
  },
  {
    question: 'What is "Banku" typically served with?',
    options: ['Groundnut soup', 'Tilapia and pepper sauce', 'Palm nut soup', 'Kontomire stew'],
    correctIndex: 1,
    category: 'Ghana Culture',
    difficulty: 'medium',
  },
  {
    question: 'The Adinkra symbol "Dwennimmen" (ram\'s horns) represents what?',
    options: ['Courage', 'Humility with strength', 'Wisdom', 'Endurance'],
    correctIndex: 1,
    category: 'Ghana Culture',
    difficulty: 'medium',
  },
  {
    question: 'Which day is traditionally associated with naming ceremonies in Akan culture?',
    options: ['The first day', 'The seventh day', 'The eighth day', 'The fourteenth day'],
    correctIndex: 2,
    category: 'Ghana Culture',
    funFact: 'Akan children are given a "day name" based on the day of the week they were born.',
    difficulty: 'medium',
  },
  {
    question: 'What is "Waakye"?',
    options: ['A type of cloth', 'Rice and beans dish', 'A festival dance', 'A greeting'],
    correctIndex: 1,
    category: 'Ghana Culture',
    difficulty: 'easy',
  },
  {
    question: 'The Hogbetsotso festival commemorates the migration of which people?',
    options: ['Ga', 'Akan', 'Ewe', 'Dagomba'],
    correctIndex: 2,
    category: 'Ghana Culture',
    funFact: 'It commemorates the Ewe escape from the tyrannical King Agorkoli of Notsie.',
    difficulty: 'hard',
  },
  {
    question: 'In Akan culture, what name is given to a boy born on Friday?',
    options: ['Kwame', 'Kofi', 'Kwadwo', 'Kweku'],
    correctIndex: 1,
    category: 'Ghana Culture',
    funFact: 'Kofi Annan, the former UN Secretary-General, was born on a Friday.',
    difficulty: 'medium',
  },
  {
    question: 'What traditional Ghanaian game involves seeds and a wooden board?',
    options: ['Ludo', 'Oware', 'Checkers', 'Dame'],
    correctIndex: 1,
    category: 'Ghana Culture',
    funFact: 'Oware is one of the oldest known games and is played across Africa.',
    difficulty: 'easy',
  },
  {
    question: 'What is "Kelewele"?',
    options: ['Fried yam', 'Spiced fried plantain', 'Grilled corn', 'Bean stew'],
    correctIndex: 1,
    category: 'Ghana Culture',
    difficulty: 'easy',
  },

  // ══════════════════════════════════════════════════════════════════
  // GOVERNMENT & CIVICS (25)
  // ══════════════════════════════════════════════════════════════════
  {
    question: 'How many regions does Ghana currently have?',
    options: ['10', '12', '14', '16'],
    correctIndex: 3,
    category: 'Government & Civics',
    difficulty: 'easy',
  },
  {
    question: 'Ghana\'s current constitution was adopted in what year?',
    options: ['1979', '1988', '1992', '1996'],
    correctIndex: 2,
    category: 'Government & Civics',
    difficulty: 'easy',
  },
  {
    question: 'How many members does Ghana\'s Parliament have?',
    options: ['200', '230', '275', '300'],
    correctIndex: 2,
    category: 'Government & Civics',
    difficulty: 'medium',
  },
  {
    question: 'What is the term length for the President of Ghana?',
    options: ['3 years', '4 years', '5 years', '6 years'],
    correctIndex: 1,
    category: 'Government & Civics',
    difficulty: 'easy',
  },
  {
    question: 'How many terms can a Ghanaian President serve?',
    options: ['One', 'Two', 'Three', 'Unlimited'],
    correctIndex: 1,
    category: 'Government & Civics',
    difficulty: 'easy',
  },
  {
    question: 'The judicial arm of Ghana\'s government is headed by which court?',
    options: ['High Court', 'Court of Appeal', 'Supreme Court', 'Circuit Court'],
    correctIndex: 2,
    category: 'Government & Civics',
    difficulty: 'easy',
  },
  {
    question: 'What is the minimum voting age in Ghana?',
    options: ['16', '18', '20', '21'],
    correctIndex: 1,
    category: 'Government & Civics',
    difficulty: 'easy',
  },
  {
    question: 'Which body oversees elections in Ghana?',
    options: ['Electoral Commission', 'National Commission for Civic Education', 'Supreme Court', 'Parliament'],
    correctIndex: 0,
    category: 'Government & Civics',
    difficulty: 'easy',
  },
  {
    question: 'The Speaker of Parliament must be elected from where?',
    options: ['Among MPs', 'Outside Parliament', 'The ruling party', 'The judiciary'],
    correctIndex: 1,
    category: 'Government & Civics',
    funFact: 'The Speaker of Parliament in Ghana must not be a sitting MP.',
    difficulty: 'hard',
  },
  {
    question: 'What percentage of votes does a presidential candidate need to win in the first round?',
    options: ['Simple majority', 'More than 50%', 'Two-thirds', '75%'],
    correctIndex: 1,
    category: 'Government & Civics',
    difficulty: 'medium',
  },
  {
    question: 'Which article of the 1992 Constitution provides for fundamental human rights?',
    options: ['Article 1-11', 'Article 12-33', 'Article 34-41', 'Article 42-56'],
    correctIndex: 1,
    category: 'Government & Civics',
    difficulty: 'hard',
  },
  {
    question: 'District Assemblies in Ghana are part of which level of governance?',
    options: ['Central', 'Regional', 'Local', 'Traditional'],
    correctIndex: 2,
    category: 'Government & Civics',
    difficulty: 'easy',
  },
  {
    question: 'The Council of State advises which arm of government?',
    options: ['Legislature', 'Judiciary', 'Executive', 'All three'],
    correctIndex: 2,
    category: 'Government & Civics',
    difficulty: 'medium',
  },
  {
    question: 'Ghana\'s currency is called what?',
    options: ['Naira', 'Cedi', 'Shilling', 'Rand'],
    correctIndex: 1,
    category: 'Government & Civics',
    funFact: 'The word "cedi" comes from the Akan word for cowrie shell.',
    difficulty: 'easy',
  },
  {
    question: 'CHRAJ stands for what?',
    options: [
      'Commission on Human Rights and Administrative Justice',
      'Center for Human Rights and Judicial Action',
      'Committee for Health, Rights and Justice',
      'Council on Human Resources and Administration of Justice',
    ],
    correctIndex: 0,
    category: 'Government & Civics',
    difficulty: 'medium',
  },
  {
    question: 'What is the role of the Auditor-General in Ghana?',
    options: ['Prosecute criminals', 'Audit public accounts', 'Advise the President', 'Draft legislation'],
    correctIndex: 1,
    category: 'Government & Civics',
    difficulty: 'medium',
  },
  {
    question: 'The National Development Planning Commission is responsible for what?',
    options: ['Military strategy', 'Economic and social development planning', 'Foreign affairs', 'Education curriculum'],
    correctIndex: 1,
    category: 'Government & Civics',
    difficulty: 'medium',
  },
  {
    question: 'Which institution manages Ghana\'s public debt?',
    options: ['Bank of Ghana', 'Ministry of Finance', 'Ghana Revenue Authority', 'Controller and Accountant General'],
    correctIndex: 1,
    category: 'Government & Civics',
    difficulty: 'hard',
  },
  {
    question: 'The Chieftaincy institution is recognized under which chapter of the Constitution?',
    options: ['Chapter 12', 'Chapter 15', 'Chapter 22', 'Chapter 27'],
    correctIndex: 2,
    category: 'Government & Civics',
    difficulty: 'hard',
  },
  {
    question: 'What type of government system does Ghana practice?',
    options: ['Parliamentary', 'Presidential', 'Semi-presidential', 'Federal'],
    correctIndex: 1,
    category: 'Government & Civics',
    difficulty: 'easy',
  },
  {
    question: 'NCCE stands for what?',
    options: [
      'National Council for Curriculum Education',
      'National Commission for Civic Education',
      'National Center for Cultural Exchange',
      'National Committee for Constitutional Enforcement',
    ],
    correctIndex: 1,
    category: 'Government & Civics',
    difficulty: 'medium',
  },
  {
    question: 'What percentage of District Assembly members are government appointees?',
    options: ['10%', '20%', '30%', '40%'],
    correctIndex: 2,
    category: 'Government & Civics',
    difficulty: 'hard',
  },
  {
    question: 'Freedom and Justice is the motto of which country?',
    options: ['Nigeria', 'Ghana', 'Kenya', 'South Africa'],
    correctIndex: 1,
    category: 'Government & Civics',
    difficulty: 'easy',
  },
  {
    question: 'Ghana\'s national anthem is titled what?',
    options: ['God Bless Our Homeland Ghana', 'Arise Ghana Youth', 'Hail the Name of Ghana', 'Ghana Our Motherland'],
    correctIndex: 0,
    category: 'Government & Civics',
    difficulty: 'easy',
  },
  {
    question: 'Which arm of government makes laws in Ghana?',
    options: ['Executive', 'Judiciary', 'Legislature (Parliament)', 'Council of State'],
    correctIndex: 2,
    category: 'Government & Civics',
    difficulty: 'easy',
  },

  // ══════════════════════════════════════════════════════════════════
  // SCIENCE & TECHNOLOGY (20)
  // ══════════════════════════════════════════════════════════════════
  {
    question: 'What does CPU stand for?',
    options: ['Central Processing Unit', 'Computer Personal Unit', 'Central Program Utility', 'Core Processing Unit'],
    correctIndex: 0,
    category: 'Science & Technology',
    difficulty: 'easy',
  },
  {
    question: 'RAM stands for what?',
    options: ['Read Access Memory', 'Random Access Memory', 'Rapid Access Module', 'Remote Access Memory'],
    correctIndex: 1,
    category: 'Science & Technology',
    difficulty: 'easy',
  },
  {
    question: 'What does HTTP stand for?',
    options: ['HyperText Transfer Protocol', 'High Transfer Text Protocol', 'HyperText Transmission Program', 'Host Transfer Text Protocol'],
    correctIndex: 0,
    category: 'Science & Technology',
    difficulty: 'easy',
  },
  {
    question: 'What is the main function of an operating system?',
    options: ['Browse the internet', 'Manage hardware and software resources', 'Create documents', 'Play games'],
    correctIndex: 1,
    category: 'Science & Technology',
    difficulty: 'easy',
  },
  {
    question: 'Which scientist is credited with the theory of relativity?',
    options: ['Isaac Newton', 'Nikola Tesla', 'Albert Einstein', 'Stephen Hawking'],
    correctIndex: 2,
    category: 'Science & Technology',
    difficulty: 'easy',
  },
  {
    question: 'What does HTML stand for?',
    options: ['HyperText Markup Language', 'High Tech Modern Language', 'HyperTransfer Markup Logic', 'Home Tool Markup Language'],
    correctIndex: 0,
    category: 'Science & Technology',
    difficulty: 'easy',
  },
  {
    question: 'What is the binary number system based on?',
    options: ['8 digits', '10 digits', '2 digits', '16 digits'],
    correctIndex: 2,
    category: 'Science & Technology',
    difficulty: 'easy',
  },
  {
    question: 'What does "www" stand for in a web address?',
    options: ['World Wide Web', 'Western Web Works', 'Wireless World Web', 'Web Window Worker'],
    correctIndex: 0,
    category: 'Science & Technology',
    difficulty: 'easy',
  },
  {
    question: 'Which gas do plants absorb during photosynthesis?',
    options: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'],
    correctIndex: 2,
    category: 'Science & Technology',
    difficulty: 'easy',
  },
  {
    question: 'What is the speed of light approximately?',
    options: ['300,000 km/s', '150,000 km/s', '1,000,000 km/s', '500,000 km/s'],
    correctIndex: 0,
    category: 'Science & Technology',
    difficulty: 'medium',
  },
  {
    question: 'What is a firewall in computing?',
    options: ['A physical barrier', 'A security system that monitors network traffic', 'A type of virus', 'A hardware component'],
    correctIndex: 1,
    category: 'Science & Technology',
    difficulty: 'easy',
  },
  {
    question: 'Which element has the chemical symbol "Au"?',
    options: ['Silver', 'Aluminum', 'Gold', 'Argon'],
    correctIndex: 2,
    category: 'Science & Technology',
    difficulty: 'medium',
  },
  {
    question: 'What does SSD stand for in computer storage?',
    options: ['Super Speed Drive', 'Solid State Drive', 'System Storage Device', 'Static Signal Drive'],
    correctIndex: 1,
    category: 'Science & Technology',
    difficulty: 'easy',
  },
  {
    question: 'What is the closest planet to the Sun?',
    options: ['Venus', 'Earth', 'Mercury', 'Mars'],
    correctIndex: 2,
    category: 'Science & Technology',
    difficulty: 'easy',
  },
  {
    question: 'What does AI stand for?',
    options: ['Automated Intelligence', 'Artificial Intelligence', 'Advanced Integration', 'Algorithmic Inference'],
    correctIndex: 1,
    category: 'Science & Technology',
    difficulty: 'easy',
  },
  {
    question: 'What is cloud computing?',
    options: ['Computing done in the sky', 'Delivering computing services over the internet', 'A type of weather simulation', 'Computing with fog machines'],
    correctIndex: 1,
    category: 'Science & Technology',
    difficulty: 'easy',
  },
  {
    question: 'Which programming language is most associated with web development?',
    options: ['Python', 'Java', 'JavaScript', 'C++'],
    correctIndex: 2,
    category: 'Science & Technology',
    difficulty: 'medium',
  },
  {
    question: 'What does DNS stand for?',
    options: ['Digital Network Service', 'Domain Name System', 'Data Network Security', 'Direct Name Server'],
    correctIndex: 1,
    category: 'Science & Technology',
    difficulty: 'medium',
  },
  {
    question: 'How many bytes are in a kilobyte?',
    options: ['100', '512', '1000', '1024'],
    correctIndex: 3,
    category: 'Science & Technology',
    funFact: 'Technically, 1 KB = 1024 bytes in binary, but 1000 in SI units (kB).',
    difficulty: 'medium',
  },
  {
    question: 'What is the chemical formula for water?',
    options: ['HO', 'H2O', 'H2O2', 'OH2'],
    correctIndex: 1,
    category: 'Science & Technology',
    difficulty: 'easy',
  },

  // ══════════════════════════════════════════════════════════════════
  // WORLD KNOWLEDGE (25)
  // ══════════════════════════════════════════════════════════════════
  {
    question: 'Which continent is the largest by land area?',
    options: ['Africa', 'North America', 'Asia', 'Europe'],
    correctIndex: 2,
    category: 'World Knowledge',
    difficulty: 'easy',
  },
  {
    question: 'The United Nations headquarters is located in which city?',
    options: ['Geneva', 'London', 'New York', 'Paris'],
    correctIndex: 2,
    category: 'World Knowledge',
    difficulty: 'easy',
  },
  {
    question: 'What is the longest river in Africa?',
    options: ['Congo', 'Niger', 'Nile', 'Zambezi'],
    correctIndex: 2,
    category: 'World Knowledge',
    difficulty: 'easy',
  },
  {
    question: 'Which country has the largest population in Africa?',
    options: ['South Africa', 'Egypt', 'Ethiopia', 'Nigeria'],
    correctIndex: 3,
    category: 'World Knowledge',
    difficulty: 'easy',
  },
  {
    question: 'The African Union headquarters is in which city?',
    options: ['Nairobi', 'Addis Ababa', 'Cairo', 'Accra'],
    correctIndex: 1,
    category: 'World Knowledge',
    difficulty: 'medium',
  },
  {
    question: 'ECOWAS stands for what?',
    options: [
      'Economic Community of West African States',
      'East and Central Organisation of World African States',
      'European Council of West African Societies',
      'Economic Council of World African Systems',
    ],
    correctIndex: 0,
    category: 'World Knowledge',
    difficulty: 'medium',
  },
  {
    question: 'Which ocean is the largest?',
    options: ['Atlantic', 'Indian', 'Pacific', 'Arctic'],
    correctIndex: 2,
    category: 'World Knowledge',
    difficulty: 'easy',
  },
  {
    question: 'Mount Kilimanjaro is located in which country?',
    options: ['Kenya', 'Tanzania', 'Uganda', 'Ethiopia'],
    correctIndex: 1,
    category: 'World Knowledge',
    difficulty: 'easy',
  },
  {
    question: 'Who was the first Secretary-General of the United Nations from Africa?',
    options: ['Kofi Annan', 'Boutros Boutros-Ghali', 'Ban Ki-moon', 'Dag Hammarskjold'],
    correctIndex: 1,
    category: 'World Knowledge',
    funFact: 'Kofi Annan was the first from sub-Saharan Africa, but Boutros-Ghali (Egypt) was first from the continent.',
    difficulty: 'hard',
  },
  {
    question: 'Which is the smallest country in Africa by land area?',
    options: ['Gambia', 'Seychelles', 'Swaziland', 'Djibouti'],
    correctIndex: 1,
    category: 'World Knowledge',
    difficulty: 'hard',
  },
  {
    question: 'The Sahara Desert is located on which continent?',
    options: ['Asia', 'Australia', 'Africa', 'South America'],
    correctIndex: 2,
    category: 'World Knowledge',
    difficulty: 'easy',
  },
  {
    question: 'What is the official language of Brazil?',
    options: ['Spanish', 'Portuguese', 'French', 'English'],
    correctIndex: 1,
    category: 'World Knowledge',
    difficulty: 'easy',
  },
  {
    question: 'Which planet is known as the Red Planet?',
    options: ['Venus', 'Jupiter', 'Mars', 'Saturn'],
    correctIndex: 2,
    category: 'World Knowledge',
    difficulty: 'easy',
  },
  {
    question: 'Nelson Mandela was the president of which country?',
    options: ['Nigeria', 'Kenya', 'Zimbabwe', 'South Africa'],
    correctIndex: 3,
    category: 'World Knowledge',
    difficulty: 'easy',
  },
  {
    question: 'What is the capital of Nigeria?',
    options: ['Lagos', 'Abuja', 'Kano', 'Ibadan'],
    correctIndex: 1,
    category: 'World Knowledge',
    difficulty: 'easy',
  },
  {
    question: 'The Great Wall was built in which country?',
    options: ['Japan', 'India', 'China', 'Mongolia'],
    correctIndex: 2,
    category: 'World Knowledge',
    difficulty: 'easy',
  },
  {
    question: 'How many countries are members of the African Union?',
    options: ['45', '50', '55', '60'],
    correctIndex: 2,
    category: 'World Knowledge',
    difficulty: 'medium',
  },
  {
    question: 'Which African country was never colonized by a European power?',
    options: ['Ghana', 'Ethiopia', 'Kenya', 'South Africa'],
    correctIndex: 1,
    category: 'World Knowledge',
    funFact: 'Ethiopia and Liberia are the only two African countries never fully colonized.',
    difficulty: 'medium',
  },
  {
    question: 'What does UNESCO stand for?',
    options: [
      'United Nations Educational, Scientific and Cultural Organization',
      'Universal Network for Education, Science and Culture Organization',
      'United Nations Environmental and Social Commission Organization',
      'Universal Nations Education and Science Committee',
    ],
    correctIndex: 0,
    category: 'World Knowledge',
    difficulty: 'medium',
  },
  {
    question: 'The Equator passes through how many African countries?',
    options: ['4', '6', '8', '10'],
    correctIndex: 1,
    category: 'World Knowledge',
    difficulty: 'hard',
  },
  {
    question: 'Who painted the Mona Lisa?',
    options: ['Michelangelo', 'Vincent van Gogh', 'Leonardo da Vinci', 'Pablo Picasso'],
    correctIndex: 2,
    category: 'World Knowledge',
    difficulty: 'easy',
  },
  {
    question: 'What year was the United Nations founded?',
    options: ['1940', '1945', '1950', '1955'],
    correctIndex: 1,
    category: 'World Knowledge',
    difficulty: 'medium',
  },
  {
    question: 'The currency of Japan is called what?',
    options: ['Yuan', 'Won', 'Yen', 'Rupee'],
    correctIndex: 2,
    category: 'World Knowledge',
    difficulty: 'easy',
  },
  {
    question: 'Which country is known as the "Land of the Rising Sun"?',
    options: ['China', 'Thailand', 'Japan', 'South Korea'],
    correctIndex: 2,
    category: 'World Knowledge',
    difficulty: 'easy',
  },
  {
    question: 'Victoria Falls is located on the border of which two countries?',
    options: ['Kenya and Tanzania', 'Zambia and Zimbabwe', 'South Africa and Namibia', 'Uganda and DR Congo'],
    correctIndex: 1,
    category: 'World Knowledge',
    difficulty: 'medium',
  },
];

/** Shuffle an array in-place (Fisher-Yates) */
export function shuffleArray<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

/** Pick N random questions, optionally filtered by category */
export function pickQuestions(count: number, category?: string): TriviaQuestion[] {
  const pool = category
    ? triviaQuestions.filter((q) => q.category === category)
    : [...triviaQuestions];
  return shuffleArray(pool).slice(0, count);
}

/** Get all unique categories */
export function getTriviaCategories(): string[] {
  return [...new Set(triviaQuestions.map((q) => q.category))];
}
